FROM nginx:1.25.1

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
    sudo \
    curl  \
    procps \
    htop \
    net-tools \
    iproute2 \
    systemctl \
    supervisor  \
    inetutils-ping \
    wget \
    ca-certificates  \
    zip  \
    unzip  \
    nano
